// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: orderbook.proto

package grpc_orderbook

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderBook_SubscribeOrderBookForSymbol_FullMethodName   = "/OrderBook/SubscribeOrderBookForSymbol"
	OrderBook_UnsubscribeOrderBookForSymbol_FullMethodName = "/OrderBook/UnsubscribeOrderBookForSymbol"
	OrderBook_GetOrderBookForSymbol_FullMethodName         = "/OrderBook/GetOrderBookForSymbol"
	OrderBook_ListSubscriptions_FullMethodName             = "/OrderBook/ListSubscriptions"
)

// OrderBookClient is the client API for OrderBook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderBookClient interface {
	SubscribeOrderBookForSymbol(ctx context.Context, in *SubscribeOrderBookRequest, opts ...grpc.CallOption) (*SubscribeOrderBookResponse, error)
	UnsubscribeOrderBookForSymbol(ctx context.Context, in *UnsubscribeOrderBookRequest, opts ...grpc.CallOption) (*UnsubscribeOrderBookResponse, error)
	GetOrderBookForSymbol(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error)
	ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error)
}

type orderBookClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderBookClient(cc grpc.ClientConnInterface) OrderBookClient {
	return &orderBookClient{cc}
}

func (c *orderBookClient) SubscribeOrderBookForSymbol(ctx context.Context, in *SubscribeOrderBookRequest, opts ...grpc.CallOption) (*SubscribeOrderBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeOrderBookResponse)
	err := c.cc.Invoke(ctx, OrderBook_SubscribeOrderBookForSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderBookClient) UnsubscribeOrderBookForSymbol(ctx context.Context, in *UnsubscribeOrderBookRequest, opts ...grpc.CallOption) (*UnsubscribeOrderBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeOrderBookResponse)
	err := c.cc.Invoke(ctx, OrderBook_UnsubscribeOrderBookForSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderBookClient) GetOrderBookForSymbol(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderBookResponse)
	err := c.cc.Invoke(ctx, OrderBook_GetOrderBookForSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderBookClient) ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubscriptionsResponse)
	err := c.cc.Invoke(ctx, OrderBook_ListSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderBookServer is the server API for OrderBook service.
// All implementations must embed UnimplementedOrderBookServer
// for forward compatibility.
type OrderBookServer interface {
	SubscribeOrderBookForSymbol(context.Context, *SubscribeOrderBookRequest) (*SubscribeOrderBookResponse, error)
	UnsubscribeOrderBookForSymbol(context.Context, *UnsubscribeOrderBookRequest) (*UnsubscribeOrderBookResponse, error)
	GetOrderBookForSymbol(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error)
	ListSubscriptions(context.Context, *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error)
	mustEmbedUnimplementedOrderBookServer()
}

// UnimplementedOrderBookServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderBookServer struct{}

func (UnimplementedOrderBookServer) SubscribeOrderBookForSymbol(context.Context, *SubscribeOrderBookRequest) (*SubscribeOrderBookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeOrderBookForSymbol not implemented")
}
func (UnimplementedOrderBookServer) UnsubscribeOrderBookForSymbol(context.Context, *UnsubscribeOrderBookRequest) (*UnsubscribeOrderBookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeOrderBookForSymbol not implemented")
}
func (UnimplementedOrderBookServer) GetOrderBookForSymbol(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderBookForSymbol not implemented")
}
func (UnimplementedOrderBookServer) ListSubscriptions(context.Context, *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubscriptions not implemented")
}
func (UnimplementedOrderBookServer) mustEmbedUnimplementedOrderBookServer() {}
func (UnimplementedOrderBookServer) testEmbeddedByValue()                   {}

// UnsafeOrderBookServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderBookServer will
// result in compilation errors.
type UnsafeOrderBookServer interface {
	mustEmbedUnimplementedOrderBookServer()
}

func RegisterOrderBookServer(s grpc.ServiceRegistrar, srv OrderBookServer) {
	// If the following call panics, it indicates UnimplementedOrderBookServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderBook_ServiceDesc, srv)
}

func _OrderBook_SubscribeOrderBookForSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderBookServer).SubscribeOrderBookForSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderBook_SubscribeOrderBookForSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderBookServer).SubscribeOrderBookForSymbol(ctx, req.(*SubscribeOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderBook_UnsubscribeOrderBookForSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderBookServer).UnsubscribeOrderBookForSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderBook_UnsubscribeOrderBookForSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderBookServer).UnsubscribeOrderBookForSymbol(ctx, req.(*UnsubscribeOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderBook_GetOrderBookForSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderBookServer).GetOrderBookForSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderBook_GetOrderBookForSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderBookServer).GetOrderBookForSymbol(ctx, req.(*GetOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderBook_ListSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderBookServer).ListSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderBook_ListSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderBookServer).ListSubscriptions(ctx, req.(*ListSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderBook_ServiceDesc is the grpc.ServiceDesc for OrderBook service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderBook_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OrderBook",
	HandlerType: (*OrderBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubscribeOrderBookForSymbol",
			Handler:    _OrderBook_SubscribeOrderBookForSymbol_Handler,
		},
		{
			MethodName: "UnsubscribeOrderBookForSymbol",
			Handler:    _OrderBook_UnsubscribeOrderBookForSymbol_Handler,
		},
		{
			MethodName: "GetOrderBookForSymbol",
			Handler:    _OrderBook_GetOrderBookForSymbol_Handler,
		},
		{
			MethodName: "ListSubscriptions",
			Handler:    _OrderBook_ListSubscriptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orderbook.proto",
}
