// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: orderbook.proto

package grpc_orderbook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrPair      string                 `protobuf:"bytes,1,opt,name=currPair,proto3" json:"currPair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOrderBookRequest) Reset() {
	*x = SubscribeOrderBookRequest{}
	mi := &file_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrderBookRequest) ProtoMessage() {}

func (x *SubscribeOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrderBookRequest.ProtoReflect.Descriptor instead.
func (*SubscribeOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeOrderBookRequest) GetCurrPair() string {
	if x != nil {
		return x.CurrPair
	}
	return ""
}

type UnsubscribeOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrPair      string                 `protobuf:"bytes,1,opt,name=currPair,proto3" json:"currPair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeOrderBookRequest) Reset() {
	*x = UnsubscribeOrderBookRequest{}
	mi := &file_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeOrderBookRequest) ProtoMessage() {}

func (x *UnsubscribeOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeOrderBookRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *UnsubscribeOrderBookRequest) GetCurrPair() string {
	if x != nil {
		return x.CurrPair
	}
	return ""
}

type GetOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrPair      string                 `protobuf:"bytes,1,opt,name=currPair,proto3" json:"currPair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_orderbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookRequest) ProtoMessage() {}

func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderBookRequest) GetCurrPair() string {
	if x != nil {
		return x.CurrPair
	}
	return ""
}

type SubscribeOrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOrderBookResponse) Reset() {
	*x = SubscribeOrderBookResponse{}
	mi := &file_orderbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrderBookResponse) ProtoMessage() {}

func (x *SubscribeOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrderBookResponse.ProtoReflect.Descriptor instead.
func (*SubscribeOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeOrderBookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnsubscribeOrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeOrderBookResponse) Reset() {
	*x = UnsubscribeOrderBookResponse{}
	mi := &file_orderbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeOrderBookResponse) ProtoMessage() {}

func (x *UnsubscribeOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeOrderBookResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeOrderBookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetOrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orderbook     string                 `protobuf:"bytes,1,opt,name=orderbook,proto3" json:"orderbook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookResponse) Reset() {
	*x = GetOrderBookResponse{}
	mi := &file_orderbook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookResponse) ProtoMessage() {}

func (x *GetOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookResponse.ProtoReflect.Descriptor instead.
func (*GetOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderBookResponse) GetOrderbook() string {
	if x != nil {
		return x.Orderbook
	}
	return ""
}

type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_orderbook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{6}
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*SubscriptionPair    `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_orderbook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*SubscriptionPair {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type SubscriptionPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  string                 `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionPair) Reset() {
	*x = SubscriptionPair{}
	mi := &file_orderbook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionPair) ProtoMessage() {}

func (x *SubscriptionPair) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionPair.ProtoReflect.Descriptor instead.
func (*SubscriptionPair) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{8}
}

func (x *SubscriptionPair) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

var File_orderbook_proto protoreflect.FileDescriptor

const file_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x0forderbook.proto\"7\n" +
	"\x19SubscribeOrderBookRequest\x12\x1a\n" +
	"\bcurrPair\x18\x01 \x01(\tR\bcurrPair\"9\n" +
	"\x1bUnsubscribeOrderBookRequest\x12\x1a\n" +
	"\bcurrPair\x18\x01 \x01(\tR\bcurrPair\"1\n" +
	"\x13GetOrderBookRequest\x12\x1a\n" +
	"\bcurrPair\x18\x01 \x01(\tR\bcurrPair\"6\n" +
	"\x1aSubscribeOrderBookResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"8\n" +
	"\x1cUnsubscribeOrderBookResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\x14GetOrderBookResponse\x12\x1c\n" +
	"\torderbook\x18\x01 \x01(\tR\torderbook\"\x1a\n" +
	"\x18ListSubscriptionsRequest\"T\n" +
	"\x19ListSubscriptionsResponse\x127\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x11.SubscriptionPairR\rsubscriptions\"6\n" +
	"\x10SubscriptionPair\x12\"\n" +
	"\fsubscription\x18\x01 \x01(\tR\fsubscription2\xdb\x02\n" +
	"\tOrderBook\x12X\n" +
	"\x1bSubscribeOrderBookForSymbol\x12\x1a.SubscribeOrderBookRequest\x1a\x1b.SubscribeOrderBookResponse\"\x00\x12^\n" +
	"\x1dUnsubscribeOrderBookForSymbol\x12\x1c.UnsubscribeOrderBookRequest\x1a\x1d.UnsubscribeOrderBookResponse\"\x00\x12F\n" +
	"\x15GetOrderBookForSymbol\x12\x14.GetOrderBookRequest\x1a\x15.GetOrderBookResponse\"\x00\x12L\n" +
	"\x11ListSubscriptions\x12\x19.ListSubscriptionsRequest\x1a\x1a.ListSubscriptionsResponse\"\x00B#Z!order-book-manager/grpc_orderbookb\x06proto3"

var (
	file_orderbook_proto_rawDescOnce sync.Once
	file_orderbook_proto_rawDescData []byte
)

func file_orderbook_proto_rawDescGZIP() []byte {
	file_orderbook_proto_rawDescOnce.Do(func() {
		file_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderbook_proto_rawDesc), len(file_orderbook_proto_rawDesc)))
	})
	return file_orderbook_proto_rawDescData
}

var file_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_orderbook_proto_goTypes = []any{
	(*SubscribeOrderBookRequest)(nil),    // 0: SubscribeOrderBookRequest
	(*UnsubscribeOrderBookRequest)(nil),  // 1: UnsubscribeOrderBookRequest
	(*GetOrderBookRequest)(nil),          // 2: GetOrderBookRequest
	(*SubscribeOrderBookResponse)(nil),   // 3: SubscribeOrderBookResponse
	(*UnsubscribeOrderBookResponse)(nil), // 4: UnsubscribeOrderBookResponse
	(*GetOrderBookResponse)(nil),         // 5: GetOrderBookResponse
	(*ListSubscriptionsRequest)(nil),     // 6: ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil),    // 7: ListSubscriptionsResponse
	(*SubscriptionPair)(nil),             // 8: SubscriptionPair
}
var file_orderbook_proto_depIdxs = []int32{
	8, // 0: ListSubscriptionsResponse.subscriptions:type_name -> SubscriptionPair
	0, // 1: OrderBook.SubscribeOrderBookForSymbol:input_type -> SubscribeOrderBookRequest
	1, // 2: OrderBook.UnsubscribeOrderBookForSymbol:input_type -> UnsubscribeOrderBookRequest
	2, // 3: OrderBook.GetOrderBookForSymbol:input_type -> GetOrderBookRequest
	6, // 4: OrderBook.ListSubscriptions:input_type -> ListSubscriptionsRequest
	3, // 5: OrderBook.SubscribeOrderBookForSymbol:output_type -> SubscribeOrderBookResponse
	4, // 6: OrderBook.UnsubscribeOrderBookForSymbol:output_type -> UnsubscribeOrderBookResponse
	5, // 7: OrderBook.GetOrderBookForSymbol:output_type -> GetOrderBookResponse
	7, // 8: OrderBook.ListSubscriptions:output_type -> ListSubscriptionsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orderbook_proto_init() }
func file_orderbook_proto_init() {
	if File_orderbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderbook_proto_rawDesc), len(file_orderbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orderbook_proto_goTypes,
		DependencyIndexes: file_orderbook_proto_depIdxs,
		MessageInfos:      file_orderbook_proto_msgTypes,
	}.Build()
	File_orderbook_proto = out.File
	file_orderbook_proto_goTypes = nil
	file_orderbook_proto_depIdxs = nil
}
